version: '3'

services:
        sonarr:
                image: lscr.io/linuxserver/sonarr
                container_name: sonarr
                environment:
                        - PUID=XXXX
                        - PGID=XXXX
                        - TZ=Europa/Bucharest
                volumes:
                        - /home/${USER}/plex-server/configs/sonarr/config:/plex-server/configs/sonarr/config
                        - /home/${USER}/plex-server/media/tv:/plex-server/media/tv
                        - /home/${USER}/plex-server/torrents/downloads:/home/torrents/downloads
                network_mode: bridge
                ports:
                        - 8989:8989
                restart: unless-stopped
        deluge:
                image: lscr.io/linuxserver/deluge
                container_name: deluge
                environment:
                        - PUID=XXXX
                        - PGID=XXXX
                        - TZ=Europa/Bucharest
                volumes:
                        - /home/${USER}/plex-server/configs/deluge/config:/plex-server/configs/deluge/config
                        - /home/${USER}/plex-server/torrents/downloads:/home/torrents/downloads
                ports:
                        - 8112:8112
                        - 6881:6881
                        - 6881:6881/udp
                restart: unless-stopped
        radarr:
                image: lscr.io/linuxserver/radarr
                container_name: radarr
                environment:
                        - PUID=XXXX
                        - PGID=XXXX
                        - TZ=Europe/Bucharest
                volumes:
                  - /home/${USER}/plex-server/configs/radarr/config:/plex-server/configs/radarr/config
                  - /home/${USER}/plex-server/media/movies:/plex-server/media/movies
                  - /home/${USER}/plex-server/torrents/downloads:/home/torrents/downloads
                ports:
                  - 7878:7878
                restart: unless-stopped
        jackett:
                image: lscr.io/linuxserver/jackett
                container_name: jackett
                environment:
                        - PUID=XXXX
                        - PGID=XXXX
                        - TZ=Europe/Bucharest
                        - AUTO_UPDATE=true #optional
                volumes:
                        - /home/${USER}/plex-server/configs/jackett/config:/plex-server/configs/jackett/config
                        - /home/${USER}/plex-server/torrents/downloads:/home/torrents/downloads
                ports:
                        - 9117:9117
                restart: unless-stopped